### ISSUE TITLE
few things I noticed

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxLineaDeTiempo#4]
moving each parameters block around made me loose some:
<img width="1040" alt="Screen Shot 2020-07-27 at 5 11 02 PM" src="https://user-images.githubusercontent.com/1054816/88592799-94b13000-d02c-11ea-855d-2ce2e2dfa23d.png">

when using many elements the window get's a bit cramped:
<img width="1030" alt="Screen Shot 2020-07-27 at 5 08 16 PM" src="https://user-images.githubusercontent.com/1054816/88592600-38e6a700-d02c-11ea-83bb-00bb0a470698.png">

timeline header changes when zooming:
<img width="1026" alt="Screen Shot 2020-07-27 at 5 08 28 PM" src="https://user-images.githubusercontent.com/1054816/88592655-51ef5800-d02c-11ea-8d6b-8a069606cd8d.png">

**Comment by roymacdonald** [comment]
Hi, thanks for your feedback.
Can you make a screen capture  video showing how to generate this issues?

> moving each parameters block around made me loose some:
It might be that it goes out of the visible area. Not sure. 

> when using many elements the window get's a bit cramped:
I know, I've need to solve that, yet I am not seeing with the latest version. Have you pulled recently from the repo?

> timeline header changes when zooming:
I dont get what you mean.

**Comment by stephanschulz** [comment]
here a video showing how the block disappears and also the keypoint drawing
https://www.dropbox.com/s/unrwlr7tyqbdu8q/blockGone.mov?dl=0

**Comment by roymacdonald** [comment]
Thanks. One thing is that you are moving the block outside the duration area, thus it disappears.  I thought there was a limit for that.
Although the strange thing is that the keypoints dissapear when you zoom. 
Are you sure that you are up to date with the repo? because I also can see some visual differences

**Comment by stephanschulz** [comment]
to make sure I just downloaded/pulled it again.
- the keypoint delete + crash thing still happens.
- the key points + lines disappearing still happens
- the parameter timeline block disappearing also still happens

**Comment by roymacdonald** [comment]
ok. thanks. 
I'll fix this right now.

**Comment by roymacdonald** [comment]
Stephan, I just pushed some fixes for the timeline blocks disapearing issue. can you please check and let me know if ti works for you?

**Comment by stephanschulz** [comment]
just downloaded the newest version.
when starting the app the time scale header still shows 8 sec but when zoom out it does adjust to correct timescale.

not all Parameters get activated when keypoint is passed by playhead
https://www.dropbox.com/s/jlx5vbw2jokn5vd/new1.mov?dl=0

**Comment by roymacdonald** [comment]
Thanks, I see. I have more or less an idea of what might be going on
